# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_bulkvectorexport.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_BulkVectorExportDialog(object):
    def setupUi(self, BulkVectorExportDialog):
        BulkVectorExportDialog.setObjectName("BulkVectorExportDialog")
        BulkVectorExportDialog.resize(620, 324)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BulkVectorExportDialog.sizePolicy().hasHeightForWidth())
        BulkVectorExportDialog.setSizePolicy(sizePolicy)
        self.buttonBox = QtWidgets.QDialogButtonBox(BulkVectorExportDialog)
        self.buttonBox.setGeometry(QtCore.QRect(220, 270, 201, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setWhatsThis("")
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.dirEdit = QtWidgets.QLineEdit(BulkVectorExportDialog)
        self.dirEdit.setGeometry(QtCore.QRect(220, 40, 331, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dirEdit.sizePolicy().hasHeightForWidth())
        self.dirEdit.setSizePolicy(sizePolicy)
        self.dirEdit.setObjectName("dirEdit")
        self.label = QtWidgets.QLabel(BulkVectorExportDialog)
        self.label.setGeometry(QtCore.QRect(10, 40, 201, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.dirButton = QtWidgets.QPushButton(BulkVectorExportDialog)
        self.dirButton.setGeometry(QtCore.QRect(560, 40, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dirButton.sizePolicy().hasHeightForWidth())
        self.dirButton.setSizePolicy(sizePolicy)
        self.dirButton.setObjectName("dirButton")
        self.compression_no = QtWidgets.QRadioButton(BulkVectorExportDialog)
        self.compression_no.setGeometry(QtCore.QRect(120, 130, 281, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compression_no.sizePolicy().hasHeightForWidth())
        self.compression_no.setSizePolicy(sizePolicy)
        self.compression_no.setChecked(True)
        self.compression_no.setObjectName("compression_no")
        self.compression_lzw = QtWidgets.QRadioButton(BulkVectorExportDialog)
        self.compression_lzw.setEnabled(True)
        self.compression_lzw.setGeometry(QtCore.QRect(120, 170, 481, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compression_lzw.sizePolicy().hasHeightForWidth())
        self.compression_lzw.setSizePolicy(sizePolicy)
        self.compression_lzw.setObjectName("compression_lzw")
        self.compression_jpeg = QtWidgets.QRadioButton(BulkVectorExportDialog)
        self.compression_jpeg.setGeometry(QtCore.QRect(120, 210, 321, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compression_jpeg.sizePolicy().hasHeightForWidth())
        self.compression_jpeg.setSizePolicy(sizePolicy)
        self.compression_jpeg.setObjectName("compression_jpeg")
        self.label_2 = QtWidgets.QLabel(BulkVectorExportDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 251, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(BulkVectorExportDialog)
        self.buttonBox.accepted.connect(BulkVectorExportDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(BulkVectorExportDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BulkVectorExportDialog)

    def retranslateUi(self, BulkVectorExportDialog):
        _translate = QtCore.QCoreApplication.translate
        BulkVectorExportDialog.setWindowTitle(_translate("BulkVectorExportDialog", "Export to file system"))
        self.label.setText(_translate("BulkVectorExportDialog", "Export to directory:"))
        self.dirButton.setText(_translate("BulkVectorExportDialog", "..."))
        self.compression_no.setToolTip(_translate("BulkVectorExportDialog", "Best option for data raster layers. BIG files!"))
        self.compression_no.setText(_translate("BulkVectorExportDialog", "No compression"))
        self.compression_lzw.setToolTip(_translate("BulkVectorExportDialog", "Compression for scientific raster data"))
        self.compression_lzw.setText(_translate("BulkVectorExportDialog", "Lossless compression (Deflate, Predictor 2)"))
        self.compression_jpeg.setToolTip(_translate("BulkVectorExportDialog", "Best option for satellite pictures"))
        self.compression_jpeg.setText(_translate("BulkVectorExportDialog", "JPEG compression 75"))
        self.label_2.setText(_translate("BulkVectorExportDialog", "GeoTIFF export options:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BulkVectorExportDialog = QtWidgets.QDialog()
    ui = Ui_BulkVectorExportDialog()
    ui.setupUi(BulkVectorExportDialog)
    BulkVectorExportDialog.show()
    sys.exit(app.exec())
